import {
  AlertTriangle,
  ArrowRight,
  AtSign,
  Bitcoin,
  Check,
  ChevronLeft,
  ChevronRight,
  DollarSign,
  File,
  FileSpreadsheet,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Moon,
  MoreVertical,
  Plus,
  Rocket,
  Send,
  Settings,
  SunMedium,
  ThumbsUp,
  Trash,
  Twitter,
  User,
  Wallet,
  X,
} from "lucide-react"

export type Icon = LucideProps

export const Icons = {
  logo: () => {

  return (
    <img className="h-8 w-8" src='src/assets/logo.svg' alt="Splice Africa Logo" />
  );
  },
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  page: File,
  media: Image,
  settings: Settings,
  invoices: FileSpreadsheet,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  bitcoin: Bitcoin,
  dollarSign: DollarSign,
  send: Send,
  rocket: Rocket,
  wallet: Wallet,
  good: ThumbsUp,
  lnAddress: AtSign,
}
